version: 2

sources:
  - name: raw
    description: "Bronze layer — raw data landed by ingestion scripts. All VARCHAR."
    database: CINEMAIQ
    schema: RAW
    tables:
      - name: raw_tmdb_movies
        columns:
          - name: TMDB_ID
            tests: [not_null]
      - name: raw_omdb_ratings
        columns:
          - name: IMDB_ID
            tests: [not_null]
      - name: raw_news_articles
        columns:
          - name: MOVIE_QUERY
            tests: [not_null]
      - name: raw_box_office
        columns:
          - name: TITLE
            tests: [not_null]
      - name: raw_google_trends
        columns:
          - name: KEYWORD
            tests: [not_null]
      - name: raw_imdb_basics
        columns:
          - name: IMDB_ID
            tests: [not_null, unique]
      - name: raw_imdb_ratings
        columns:
          - name: IMDB_ID
            tests: [not_null, unique]